/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Cuisine1
 */
export interface Cuisine1 {}

/**
 * Check if a given object implements the Cuisine1 interface.
 */
export function instanceOfCuisine1(value: object): boolean {
  return true;
}

export function Cuisine1FromJSON(json: any): Cuisine1 {
  return Cuisine1FromJSONTyped(json, false);
}

export function Cuisine1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Cuisine1 {
  return json;
}

export function Cuisine1ToJSON(value?: Cuisine1 | null): any {
  return value;
}
