/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Id1
 */
export interface Id1 {}

/**
 * Check if a given object implements the Id1 interface.
 */
export function instanceOfId1(value: object): boolean {
  return true;
}

export function Id1FromJSON(json: any): Id1 {
  return Id1FromJSONTyped(json, false);
}

export function Id1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Id1 {
  return json;
}

export function Id1ToJSON(value?: Id1 | null): any {
  return value;
}
