/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The unique identifier of the review
 * @export
 * @interface Id3
 */
export interface Id3 {
}

/**
 * Check if a given object implements the Id3 interface.
 */
export function instanceOfId3(value: object): boolean {
    return true;
}

export function Id3FromJSON(json: any): Id3 {
    return Id3FromJSONTyped(json, false);
}

export function Id3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Id3 {
    return json;
}

export function Id3ToJSON(value?: Id3 | null): any {
    return value;
}

