/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Location
 */
export interface Location {}

/**
 * Check if a given object implements the Location interface.
 */
export function instanceOfLocation(value: object): boolean {
  return true;
}

export function LocationFromJSON(json: any): Location {
  return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Location {
  return json;
}

export function LocationToJSON(value?: Location | null): any {
  return value;
}
