/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PartySize
 */
export interface PartySize {}

/**
 * Check if a given object implements the PartySize interface.
 */
export function instanceOfPartySize(value: object): boolean {
  return true;
}

export function PartySizeFromJSON(json: any): PartySize {
  return PartySizeFromJSONTyped(json, false);
}

export function PartySizeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PartySize {
  return json;
}

export function PartySizeToJSON(value?: PartySize | null): any {
  return value;
}
