/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhoneNumber1
 */
export interface PhoneNumber1 {
}

/**
 * Check if a given object implements the PhoneNumber1 interface.
 */
export function instanceOfPhoneNumber1(value: object): boolean {
    return true;
}

export function PhoneNumber1FromJSON(json: any): PhoneNumber1 {
    return PhoneNumber1FromJSONTyped(json, false);
}

export function PhoneNumber1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneNumber1 {
    return json;
}

export function PhoneNumber1ToJSON(value?: PhoneNumber1 | null): any {
    return value;
}

