/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReservationTime
 */
export interface ReservationTime {}

/**
 * Check if a given object implements the ReservationTime interface.
 */
export function instanceOfReservationTime(value: object): boolean {
  return true;
}

export function ReservationTimeFromJSON(json: any): ReservationTime {
  return ReservationTimeFromJSONTyped(json, false);
}

export function ReservationTimeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReservationTime {
  return json;
}

export function ReservationTimeToJSON(value?: ReservationTime | null): any {
  return value;
}
