/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Restaurant
 */
export interface Restaurant {
  /**
   *
   * @type {number}
   * @memberof Restaurant
   */
  id?: number;
  /**
   * The name of the alembic
   * @type {string}
   * @memberof Restaurant
   */
  name: string;
  /**
   * The physical location of the alembic
   * @type {string}
   * @memberof Restaurant
   */
  location: string;
  /**
   *
   * @type {string}
   * @memberof Restaurant
   */
  cuisine?: string;
  /**
   *
   * @type {number}
   * @memberof Restaurant
   */
  rating?: number;
  /**
   *
   * @type {string}
   * @memberof Restaurant
   */
  priceRange?: string;
}

/**
 * Check if a given object implements the Restaurant interface.
 */
export function instanceOfRestaurant(value: object): boolean {
  if (!("name" in value)) return false;
  if (!("location" in value)) return false;
  return true;
}

export function RestaurantFromJSON(json: any): Restaurant {
  return RestaurantFromJSONTyped(json, false);
}

export function RestaurantFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Restaurant {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"],
    location: json["location"],
    cuisine: json["cuisine"] == null ? undefined : json["cuisine"],
    rating: json["rating"] == null ? undefined : json["rating"],
    priceRange: json["price_range"] == null ? undefined : json["price_range"],
  };
}

export function RestaurantToJSON(value?: Restaurant | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    name: value["name"],
    location: value["location"],
    cuisine: value["cuisine"],
    rating: value["rating"],
    price_range: value["priceRange"],
  };
}
