/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Role1
 */
export interface Role1 {}

/**
 * Check if a given object implements the Role1 interface.
 */
export function instanceOfRole1(value: object): boolean {
  return true;
}

export function Role1FromJSON(json: any): Role1 {
  return Role1FromJSONTyped(json, false);
}

export function Role1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Role1 {
  return json;
}

export function Role1ToJSON(value?: Role1 | null): any {
  return value;
}
