/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SpecialRequests1
 */
export interface SpecialRequests1 {}

/**
 * Check if a given object implements the SpecialRequests1 interface.
 */
export function instanceOfSpecialRequests1(value: object): boolean {
  return true;
}

export function SpecialRequests1FromJSON(json: any): SpecialRequests1 {
  return SpecialRequests1FromJSONTyped(json, false);
}

export function SpecialRequests1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SpecialRequests1 {
  return json;
}

export function SpecialRequests1ToJSON(value?: SpecialRequests1 | null): any {
  return value;
}
