/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserId
 */
export interface UserId {}

/**
 * Check if a given object implements the UserId interface.
 */
export function instanceOfUserId(value: object): boolean {
  return true;
}

export function UserIdFromJSON(json: any): UserId {
  return UserIdFromJSONTyped(json, false);
}

export function UserIdFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserId {
  return json;
}

export function UserIdToJSON(value?: UserId | null): any {
  return value;
}
