/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Username
 */
export interface Username {
}

/**
 * Check if a given object implements the Username interface.
 */
export function instanceOfUsername(value: object): boolean {
    return true;
}

export function UsernameFromJSON(json: any): Username {
    return UsernameFromJSONTyped(json, false);
}

export function UsernameFromJSONTyped(json: any, ignoreDiscriminator: boolean): Username {
    return json;
}

export function UsernameToJSON(value?: Username | null): any {
    return value;
}

