# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_reservation_reservation_post(self) -> None:
        """Test case for create_reservation_reservation_post

        Create Reservation
        """
        pass

    def test_create_reservations_reservations_post(self) -> None:
        """Test case for create_reservations_reservations_post

        Create Reservations
        """
        pass

    def test_create_restaurant_restaurant_post(self) -> None:
        """Test case for create_restaurant_restaurant_post

        Create Restaurant
        """
        pass

    def test_create_restaurants_restaurants_post(self) -> None:
        """Test case for create_restaurants_restaurants_post

        Create Restaurants
        """
        pass

    def test_create_review_review_post(self) -> None:
        """Test case for create_review_review_post

        Create Review
        """
        pass

    def test_create_reviews_reviews_post(self) -> None:
        """Test case for create_reviews_reviews_post

        Create Reviews
        """
        pass

    def test_create_user_user_post(self) -> None:
        """Test case for create_user_user_post

        Create User
        """
        pass

    def test_create_users_users_post(self) -> None:
        """Test case for create_users_users_post

        Create Users
        """
        pass

    def test_delete_reservation_reservation_delete(self) -> None:
        """Test case for delete_reservation_reservation_delete

        Delete Reservation
        """
        pass

    def test_delete_reservations_reservations_delete(self) -> None:
        """Test case for delete_reservations_reservations_delete

        Delete Reservations
        """
        pass

    def test_delete_restaurant_restaurant_delete(self) -> None:
        """Test case for delete_restaurant_restaurant_delete

        Delete Restaurant
        """
        pass

    def test_delete_restaurants_restaurants_delete(self) -> None:
        """Test case for delete_restaurants_restaurants_delete

        Delete Restaurants
        """
        pass

    def test_delete_review_review_delete(self) -> None:
        """Test case for delete_review_review_delete

        Delete Review
        """
        pass

    def test_delete_reviews_reviews_delete(self) -> None:
        """Test case for delete_reviews_reviews_delete

        Delete Reviews
        """
        pass

    def test_delete_user_user_delete(self) -> None:
        """Test case for delete_user_user_delete

        Delete User
        """
        pass

    def test_delete_users_users_delete(self) -> None:
        """Test case for delete_users_users_delete

        Delete Users
        """
        pass

    def test_get_reservation_reservation_get(self) -> None:
        """Test case for get_reservation_reservation_get

        Get Reservation
        """
        pass

    def test_get_reservations_reservations_get(self) -> None:
        """Test case for get_reservations_reservations_get

        Get Reservations
        """
        pass

    def test_get_restaurant_restaurant_get(self) -> None:
        """Test case for get_restaurant_restaurant_get

        Get Restaurant
        """
        pass

    def test_get_restaurants_restaurants_get(self) -> None:
        """Test case for get_restaurants_restaurants_get

        Get Restaurants
        """
        pass

    def test_get_review_review_get(self) -> None:
        """Test case for get_review_review_get

        Get Review
        """
        pass

    def test_get_reviews_reviews_get(self) -> None:
        """Test case for get_reviews_reviews_get

        Get Reviews
        """
        pass

    def test_get_user_user_get(self) -> None:
        """Test case for get_user_user_get

        Get User
        """
        pass

    def test_get_users_users_get(self) -> None:
        """Test case for get_users_users_get

        Get Users
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass

    def test_update_reservation_reservation_put(self) -> None:
        """Test case for update_reservation_reservation_put

        Update Reservation
        """
        pass

    def test_update_reservations_reservations_put(self) -> None:
        """Test case for update_reservations_reservations_put

        Update Reservations
        """
        pass

    def test_update_restaurant_restaurant_put(self) -> None:
        """Test case for update_restaurant_restaurant_put

        Update Restaurant
        """
        pass

    def test_update_restaurants_restaurants_put(self) -> None:
        """Test case for update_restaurants_restaurants_put

        Update Restaurants
        """
        pass

    def test_update_review_review_put(self) -> None:
        """Test case for update_review_review_put

        Update Review
        """
        pass

    def test_update_reviews_reviews_put(self) -> None:
        """Test case for update_reviews_reviews_put

        Update Reviews
        """
        pass

    def test_update_user_user_put(self) -> None:
        """Test case for update_user_user_put

        Update User
        """
        pass

    def test_update_users_users_put(self) -> None:
        """Test case for update_users_users_put

        Update Users
        """
        pass


if __name__ == "__main__":
    unittest.main()
