/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Query model for Reservation
 * @export
 * @interface ReservationQuery
 */
export interface ReservationQuery {
  /**
   *
   * @type {number}
   * @memberof ReservationQuery
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof ReservationQuery
   */
  restaurantId?: number;
  /**
   *
   * @type {number}
   * @memberof ReservationQuery
   */
  userId?: number;
  /**
   *
   * @type {Date}
   * @memberof ReservationQuery
   */
  reservationTime?: Date;
  /**
   *
   * @type {number}
   * @memberof ReservationQuery
   */
  partySize?: number;
  /**
   *
   * @type {string}
   * @memberof ReservationQuery
   */
  specialRequests?: string;
}

/**
 * Check if a given object implements the ReservationQuery interface.
 */
export function instanceOfReservationQuery(value: object): boolean {
  return true;
}

export function ReservationQueryFromJSON(json: any): ReservationQuery {
  return ReservationQueryFromJSONTyped(json, false);
}

export function ReservationQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReservationQuery {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    restaurantId:
      json["restaurant_id"] == null ? undefined : json["restaurant_id"],
    userId: json["user_id"] == null ? undefined : json["user_id"],
    reservationTime:
      json["reservation_time"] == null
        ? undefined
        : new Date(json["reservation_time"]),
    partySize: json["party_size"] == null ? undefined : json["party_size"],
    specialRequests:
      json["special_requests"] == null ? undefined : json["special_requests"],
  };
}

export function ReservationQueryToJSON(value?: ReservationQuery | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    restaurant_id: value["restaurantId"],
    user_id: value["userId"],
    reservation_time:
      value["reservationTime"] == null
        ? undefined
        : (value["reservationTime"] as any).toISOString(),
    party_size: value["partySize"],
    special_requests: value["specialRequests"],
  };
}
