/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Query model for Review
 * @export
 * @interface ReviewQuery
 */
export interface ReviewQuery {
  /**
   *
   * @type {number}
   * @memberof ReviewQuery
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof ReviewQuery
   */
  restaurantId?: number;
  /**
   *
   * @type {number}
   * @memberof ReviewQuery
   */
  userId?: number;
  /**
   *
   * @type {number}
   * @memberof ReviewQuery
   */
  rating?: number;
  /**
   *
   * @type {string}
   * @memberof ReviewQuery
   */
  comment?: string;
}

/**
 * Check if a given object implements the ReviewQuery interface.
 */
export function instanceOfReviewQuery(value: object): boolean {
  return true;
}

export function ReviewQueryFromJSON(json: any): ReviewQuery {
  return ReviewQueryFromJSONTyped(json, false);
}

export function ReviewQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReviewQuery {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    restaurantId:
      json["restaurant_id"] == null ? undefined : json["restaurant_id"],
    userId: json["user_id"] == null ? undefined : json["user_id"],
    rating: json["rating"] == null ? undefined : json["rating"],
    comment: json["comment"] == null ? undefined : json["comment"],
  };
}

export function ReviewQueryToJSON(value?: ReviewQuery | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    restaurant_id: value["restaurantId"],
    user_id: value["userId"],
    rating: value["rating"],
    comment: value["comment"],
  };
}
