/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Query model for User
 * @export
 * @interface UserQuery
 */
export interface UserQuery {
  /**
   *
   * @type {number}
   * @memberof UserQuery
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof UserQuery
   */
  username?: string;
  /**
   *
   * @type {string}
   * @memberof UserQuery
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UserQuery
   */
  phoneNumber?: string;
  /**
   *
   * @type {Array<any>}
   * @memberof UserQuery
   */
  preferences?: Array<any>;
  /**
   *
   * @type {string}
   * @memberof UserQuery
   */
  role?: string;
}

/**
 * Check if a given object implements the UserQuery interface.
 */
export function instanceOfUserQuery(value: object): boolean {
  return true;
}

export function UserQueryFromJSON(json: any): UserQuery {
  return UserQueryFromJSONTyped(json, false);
}

export function UserQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserQuery {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    username: json["username"] == null ? undefined : json["username"],
    email: json["email"] == null ? undefined : json["email"],
    phoneNumber:
      json["phone_number"] == null ? undefined : json["phone_number"],
    preferences: json["preferences"] == null ? undefined : json["preferences"],
    role: json["role"] == null ? undefined : json["role"],
  };
}

export function UserQueryToJSON(value?: UserQuery | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    username: value["username"],
    email: value["email"],
    phone_number: value["phoneNumber"],
    preferences: value["preferences"],
    role: value["role"],
  };
}
