/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {number}
   * @memberof User
   */
  id?: number;
  /**
   * The username of the user
   * @type {string}
   * @memberof User
   */
  username: string;
  /**
   * The email address of the user
   * @type {string}
   * @memberof User
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  phoneNumber?: string;
  /**
   *
   * @type {Array<any>}
   * @memberof User
   */
  preferences?: Array<any>;
  /**
   *
   * @type {string}
   * @memberof User
   */
  role?: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
  if (!("username" in value)) return false;
  if (!("email" in value)) return false;
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): User {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    username: json["username"],
    email: json["email"],
    phoneNumber:
      json["phone_number"] == null ? undefined : json["phone_number"],
    preferences: json["preferences"] == null ? undefined : json["preferences"],
    role: json["role"] == null ? undefined : json["role"],
  };
}

export function UserToJSON(value?: User | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value["id"],
    username: value["username"],
    email: value["email"],
    phone_number: value["phoneNumber"],
    preferences: value["preferences"],
    role: value["role"],
  };
}
