/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The type of cuisine the restaurant offers
 * @export
 * @interface Cuisine
 */
export interface Cuisine {}

/**
 * Check if a given object implements the Cuisine interface.
 */
export function instanceOfCuisine(value: object): boolean {
  return true;
}

export function CuisineFromJSON(json: any): Cuisine {
  return CuisineFromJSONTyped(json, false);
}

export function CuisineFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Cuisine {
  return json;
}

export function CuisineToJSON(value?: Cuisine | null): any {
  return value;
}
