# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_group_group_post(self) -> None:
        """Test case for create_group_group_post

        Create Group
        """
        pass

    def test_create_groups_groups_post(self) -> None:
        """Test case for create_groups_groups_post

        Create Groups
        """
        pass

    def test_create_user_user_post(self) -> None:
        """Test case for create_user_user_post

        Create User
        """
        pass

    def test_create_users_users_post(self) -> None:
        """Test case for create_users_users_post

        Create Users
        """
        pass

    def test_delete_group_group_delete(self) -> None:
        """Test case for delete_group_group_delete

        Delete Group
        """
        pass

    def test_delete_groups_groups_delete(self) -> None:
        """Test case for delete_groups_groups_delete

        Delete Groups
        """
        pass

    def test_delete_user_user_delete(self) -> None:
        """Test case for delete_user_user_delete

        Delete User
        """
        pass

    def test_delete_users_users_delete(self) -> None:
        """Test case for delete_users_users_delete

        Delete Users
        """
        pass

    def test_get_group_group_get(self) -> None:
        """Test case for get_group_group_get

        Get Group
        """
        pass

    def test_get_groups_groups_get(self) -> None:
        """Test case for get_groups_groups_get

        Get Groups
        """
        pass

    def test_get_user_user_get(self) -> None:
        """Test case for get_user_user_get

        Get User
        """
        pass

    def test_get_users_users_get(self) -> None:
        """Test case for get_users_users_get

        Get Users
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass

    def test_update_group_group_put(self) -> None:
        """Test case for update_group_group_put

        Update Group
        """
        pass

    def test_update_groups_groups_put(self) -> None:
        """Test case for update_groups_groups_put

        Update Groups
        """
        pass

    def test_update_user_user_put(self) -> None:
        """Test case for update_user_user_put

        Update User
        """
        pass

    def test_update_users_users_put(self) -> None:
        """Test case for update_users_users_put

        Update Users
        """
        pass


if __name__ == "__main__":
    unittest.main()
