/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The unique identifier of the user
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * The username of the user
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * The email of the user
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * The location of the user
     * @type {string}
     * @memberof User
     */
    location?: string;
    /**
     * The age of the user
     * @type {number}
     * @memberof User
     */
    age?: number;
    /**
     * The team name of the user
     * @type {string}
     * @memberof User
     */
    team?: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    if (!('username' in value)) return false;
    if (!('email' in value)) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'],
        'email': json['email'],
        'location': json['location'] == null ? undefined : json['location'],
        'age': json['age'] == null ? undefined : json['age'],
        'team': json['team'] == null ? undefined : json['team'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'location': value['location'],
        'age': value['age'],
        'team': value['team'],
    };
}

