# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class ReservationQuery(BaseModel):
    """
    ReservationQuery
    """  # noqa: E501

    id: Optional[StrictInt] = None
    restaurant_id: Optional[StrictInt] = None
    user_id: Optional[StrictInt] = None
    reservation_time: Optional[datetime] = None
    party_size: Optional[StrictInt] = None
    special_requests: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "restaurant_id",
        "user_id",
        "reservation_time",
        "party_size",
        "special_requests",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReservationQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict["id"] = None

        # set to None if restaurant_id (nullable) is None
        # and model_fields_set contains the field
        if self.restaurant_id is None and "restaurant_id" in self.model_fields_set:
            _dict["restaurant_id"] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict["user_id"] = None

        # set to None if reservation_time (nullable) is None
        # and model_fields_set contains the field
        if (
            self.reservation_time is None
            and "reservation_time" in self.model_fields_set
        ):
            _dict["reservation_time"] = None

        # set to None if party_size (nullable) is None
        # and model_fields_set contains the field
        if self.party_size is None and "party_size" in self.model_fields_set:
            _dict["party_size"] = None

        # set to None if special_requests (nullable) is None
        # and model_fields_set contains the field
        if (
            self.special_requests is None
            and "special_requests" in self.model_fields_set
        ):
            _dict["special_requests"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReservationQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "restaurant_id": obj.get("restaurant_id"),
                "user_id": obj.get("user_id"),
                "reservation_time": obj.get("reservation_time"),
                "party_size": obj.get("party_size"),
                "special_requests": obj.get("special_requests"),
            }
        )
        return _obj
