# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_async_user_async_post(self) -> None:
        """Test case for create_user_async_user_async_post

        Create User Async
        """
        pass

    def test_create_user_user_post(self) -> None:
        """Test case for create_user_user_post

        Create User
        """
        pass

    def test_create_users_async_users_async_post(self) -> None:
        """Test case for create_users_async_users_async_post

        Create Users Async
        """
        pass

    def test_create_users_users_post(self) -> None:
        """Test case for create_users_users_post

        Create Users
        """
        pass

    def test_delete_user_async_user_async_delete(self) -> None:
        """Test case for delete_user_async_user_async_delete

        Delete User Async
        """
        pass

    def test_delete_user_user_delete(self) -> None:
        """Test case for delete_user_user_delete

        Delete User
        """
        pass

    def test_delete_users_async_users_async_delete(self) -> None:
        """Test case for delete_users_async_users_async_delete

        Delete Users Async
        """
        pass

    def test_delete_users_users_delete(self) -> None:
        """Test case for delete_users_users_delete

        Delete Users
        """
        pass

    def test_get_user_user_get(self) -> None:
        """Test case for get_user_user_get

        Get User
        """
        pass

    def test_get_users_users_get(self) -> None:
        """Test case for get_users_users_get

        Get Users
        """
        pass

    def test_update_user_async_user_async_put(self) -> None:
        """Test case for update_user_async_user_async_put

        Update User Async
        """
        pass

    def test_update_user_user_put(self) -> None:
        """Test case for update_user_user_put

        Update User
        """
        pass

    def test_update_users_async_users_async_put(self) -> None:
        """Test case for update_users_async_users_async_put

        Update Users Async
        """
        pass

    def test_update_users_users_put(self) -> None:
        """Test case for update_users_users_put

        Update Users
        """
        pass


if __name__ == "__main__":
    unittest.main()
