# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_query import UserQuery


class TestUserQuery(unittest.TestCase):
    """UserQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserQuery:
        """Test UserQuery
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserQuery`
        """
        model = UserQuery()
        if include_optional:
            return UserQuery(
                id = 56,
                username = '',
                email = '',
                phone_number = '',
                preferences = [
                    null
                    ],
                role = ''
            )
        else:
            return UserQuery(
        )
        """

    def testUserQuery(self):
        """Test UserQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
