# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reservation_query import ReservationQuery


class TestReservationQuery(unittest.TestCase):
    """ReservationQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReservationQuery:
        """Test ReservationQuery
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReservationQuery`
        """
        model = ReservationQuery()
        if include_optional:
            return ReservationQuery(
                id = 56,
                restaurant_id = 56,
                user_id = 56,
                reservation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                party_size = 56,
                special_requests = ''
            )
        else:
            return ReservationQuery(
        )
        """

    def testReservationQuery(self):
        """Test ReservationQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
