# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.reservation_api import ReservationApi


class TestReservationApi(unittest.TestCase):
    """ReservationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReservationApi()

    def tearDown(self) -> None:
        pass

    def test_create_reservation_async_reservation_async_post(self) -> None:
        """Test case for create_reservation_async_reservation_async_post

        Create Reservation Async
        """
        pass

    def test_create_reservation_reservation_post(self) -> None:
        """Test case for create_reservation_reservation_post

        Create Reservation
        """
        pass

    def test_create_reservations_async_reservations_async_post(self) -> None:
        """Test case for create_reservations_async_reservations_async_post

        Create Reservations Async
        """
        pass

    def test_create_reservations_reservations_post(self) -> None:
        """Test case for create_reservations_reservations_post

        Create Reservations
        """
        pass

    def test_delete_reservation_async_reservation_async_delete(self) -> None:
        """Test case for delete_reservation_async_reservation_async_delete

        Delete Reservation Async
        """
        pass

    def test_delete_reservation_reservation_delete(self) -> None:
        """Test case for delete_reservation_reservation_delete

        Delete Reservation
        """
        pass

    def test_delete_reservations_async_reservations_async_delete(self) -> None:
        """Test case for delete_reservations_async_reservations_async_delete

        Delete Reservations Async
        """
        pass

    def test_delete_reservations_reservations_delete(self) -> None:
        """Test case for delete_reservations_reservations_delete

        Delete Reservations
        """
        pass

    def test_get_reservation_reservation_get(self) -> None:
        """Test case for get_reservation_reservation_get

        Get Reservation
        """
        pass

    def test_get_reservations_reservations_get(self) -> None:
        """Test case for get_reservations_reservations_get

        Get Reservations
        """
        pass

    def test_query_reservation_reservation_query_post(self) -> None:
        """Test case for query_reservation_reservation_query_post

        Query Reservation
        """
        pass

    def test_update_reservation_async_reservation_async_put(self) -> None:
        """Test case for update_reservation_async_reservation_async_put

        Update Reservation Async
        """
        pass

    def test_update_reservation_reservation_put(self) -> None:
        """Test case for update_reservation_reservation_put

        Update Reservation
        """
        pass

    def test_update_reservations_async_reservations_async_put(self) -> None:
        """Test case for update_reservations_async_reservations_async_put

        Update Reservations Async
        """
        pass

    def test_update_reservations_reservations_put(self) -> None:
        """Test case for update_reservations_reservations_put

        Update Reservations
        """
        pass


if __name__ == "__main__":
    unittest.main()
