# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.review_api import ReviewApi


class TestReviewApi(unittest.TestCase):
    """ReviewApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReviewApi()

    def tearDown(self) -> None:
        pass

    def test_create_review_async_review_async_post(self) -> None:
        """Test case for create_review_async_review_async_post

        Create Review Async
        """
        pass

    def test_create_review_review_post(self) -> None:
        """Test case for create_review_review_post

        Create Review
        """
        pass

    def test_create_reviews_async_reviews_async_post(self) -> None:
        """Test case for create_reviews_async_reviews_async_post

        Create Reviews Async
        """
        pass

    def test_create_reviews_reviews_post(self) -> None:
        """Test case for create_reviews_reviews_post

        Create Reviews
        """
        pass

    def test_delete_review_async_review_async_delete(self) -> None:
        """Test case for delete_review_async_review_async_delete

        Delete Review Async
        """
        pass

    def test_delete_review_review_delete(self) -> None:
        """Test case for delete_review_review_delete

        Delete Review
        """
        pass

    def test_delete_reviews_async_reviews_async_delete(self) -> None:
        """Test case for delete_reviews_async_reviews_async_delete

        Delete Reviews Async
        """
        pass

    def test_delete_reviews_reviews_delete(self) -> None:
        """Test case for delete_reviews_reviews_delete

        Delete Reviews
        """
        pass

    def test_get_review_review_get(self) -> None:
        """Test case for get_review_review_get

        Get Review
        """
        pass

    def test_get_reviews_reviews_get(self) -> None:
        """Test case for get_reviews_reviews_get

        Get Reviews
        """
        pass

    def test_update_review_async_review_async_put(self) -> None:
        """Test case for update_review_async_review_async_put

        Update Review Async
        """
        pass

    def test_update_review_review_put(self) -> None:
        """Test case for update_review_review_put

        Update Review
        """
        pass

    def test_update_reviews_async_reviews_async_put(self) -> None:
        """Test case for update_reviews_async_reviews_async_put

        Update Reviews Async
        """
        pass

    def test_update_reviews_reviews_put(self) -> None:
        """Test case for update_reviews_reviews_put

        Update Reviews
        """
        pass


if __name__ == "__main__":
    unittest.main()
