# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.restaurant_api import RestaurantApi


class TestRestaurantApi(unittest.TestCase):
    """RestaurantApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RestaurantApi()

    def tearDown(self) -> None:
        pass

    def test_create_restaurant_async_restaurant_async_post(self) -> None:
        """Test case for create_restaurant_async_restaurant_async_post

        Create Restaurant Async
        """
        pass

    def test_create_restaurant_restaurant_post(self) -> None:
        """Test case for create_restaurant_restaurant_post

        Create Restaurant
        """
        pass

    def test_create_restaurants_async_restaurants_async_post(self) -> None:
        """Test case for create_restaurants_async_restaurants_async_post

        Create Restaurants Async
        """
        pass

    def test_create_restaurants_restaurants_post(self) -> None:
        """Test case for create_restaurants_restaurants_post

        Create Restaurants
        """
        pass

    def test_delete_restaurant_async_restaurant_async_delete(self) -> None:
        """Test case for delete_restaurant_async_restaurant_async_delete

        Delete Restaurant Async
        """
        pass

    def test_delete_restaurant_restaurant_delete(self) -> None:
        """Test case for delete_restaurant_restaurant_delete

        Delete Restaurant
        """
        pass

    def test_delete_restaurants_async_restaurants_async_delete(self) -> None:
        """Test case for delete_restaurants_async_restaurants_async_delete

        Delete Restaurants Async
        """
        pass

    def test_delete_restaurants_restaurants_delete(self) -> None:
        """Test case for delete_restaurants_restaurants_delete

        Delete Restaurants
        """
        pass

    def test_get_restaurant_restaurant_get(self) -> None:
        """Test case for get_restaurant_restaurant_get

        Get Restaurant
        """
        pass

    def test_get_restaurants_restaurants_get(self) -> None:
        """Test case for get_restaurants_restaurants_get

        Get Restaurants
        """
        pass

    def test_update_restaurant_async_restaurant_async_put(self) -> None:
        """Test case for update_restaurant_async_restaurant_async_put

        Update Restaurant Async
        """
        pass

    def test_update_restaurant_restaurant_put(self) -> None:
        """Test case for update_restaurant_restaurant_put

        Update Restaurant
        """
        pass

    def test_update_restaurants_async_restaurants_async_put(self) -> None:
        """Test case for update_restaurants_async_restaurants_async_put

        Update Restaurants Async
        """
        pass

    def test_update_restaurants_restaurants_put(self) -> None:
        """Test case for update_restaurants_restaurants_put

        Update Restaurants
        """
        pass


if __name__ == "__main__":
    unittest.main()
