name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Setup test MYSQL Database
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          architecture: 'x64'

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Run tests
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Backend Dependencies
        run: |
          echo "Installing Backend Dependencies"
          python -m pip install --upgrade pip
          pip install poetry coverage
          poetry install

      # Create necessary databases
      - name: Create Additional Databases
        run: |
          mysql --host 127.0.0.1 --port 3306 --user root --password=root -e "CREATE DATABASE IF NOT EXISTS test_events_app;"
          mysql --host 127.0.0.1 --port 3306 --user root --password=root -e "CREATE DATABASE IF NOT EXISTS test_restaurant_app;"

      # Run tests for the sample apps
      - name: Test Sample Events App
        run: |
          echo "Running Tests"
          export VERBOSE=1
          # Set database connection environment variables if not set in the test configs
          export DB_HOST=127.0.0.1
          export DB_PORT=3306
          export DB_USER=root
          export DB_PASSWORD=root
          export DB_NAME=test_events_app
          # Run Tests
          poetry run coverage run -m pytest builder/tests/test_events_app.py --verbose
          poetry run coverage report -m

      - name: Test Sample Restaurant App
        run: |
          echo "Running Tests"
          export VERBOSE=1
          # Set database connection environment variables if not set in the test configs
          export DB_HOST=127.0.0.1
          export DB_PORT=3306
          export DB_USER=root
          export DB_PASSWORD=root
          export DB_NAME=test_restaurant_app        
          # Run Tests
          poetry run coverage run -m pytest builder/tests/test_restaurant_app.py --verbose
          poetry run coverage report -m

      # Run unit tests
      - name: Run Unit Tests
        run: |
          echo "Running Unit Tests"
          poetry run coverage run -m pytest builder/generate --verbose
          poetry run coverage report -m
