name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
          architecture: 'x64'

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Run tests
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Backend Dependencies
        run: |
          echo "Installing Backend Dependencies"
          python -m pip install --upgrade pip
          pip install poetry coverage
          poetry install

      # Run backend + frontend tests
      - name: Run Tests
        run: |
          echo "Running Tests"
          export VERBOSE=1
          poetry run coverage run -m pytest builder/
          poetry run coverage report -m
